/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Font;
import java.util.Calendar;
import java.util.Date;
import java.util.Random;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import model.Encounter;
import model.EncounterHistory;
import model.Patient;
import model.PatientDirectory;
import model.Person;
import model.PersonDirectory;
import model.VitalSigns;

/**
 *
 * @author deepv
 */
public class ParentPanel extends javax.swing.JPanel {

    PersonDirectory people;
    PatientDirectory patientDir;
    EncounterHistory encounterHistory;
    int id;

    /**
     * Creates new form ParentPanel
     */
    public ParentPanel(PersonDirectory people, PatientDirectory patientDir, EncounterHistory encounterHistory) {
        initComponents();
        this.people = people;
        this.patientDir = patientDir;
        this.encounterHistory = encounterHistory;

        btnPreviousReports.setVisible(false);
        pnlTable.setVisible(false);

        // Populate the JTable
        if (this.people != null) {
            populateTable();
        }

        // Style the JTable header
        JTableHeader tableHeader = tblDashboard.getTableHeader();
        tableHeader.setFont(new Font("Segoe UI", Font.BOLD, 12));
        ((DefaultTableCellRenderer) tableHeader.getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        ViewAllProfilePanel = new javax.swing.JPanel();
        lblBorder4 = new javax.swing.JLabel();
        lblBorder2 = new javax.swing.JLabel();
        lblHeader1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDashboard = new javax.swing.JTable();
        btnAddVitals = new javax.swing.JButton();
        btnCreateProfile = new javax.swing.JButton();
        CreateProfilePanel = new javax.swing.JPanel();
        lblBorder3 = new javax.swing.JLabel();
        lblBorder1 = new javax.swing.JLabel();
        lblHeader = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        lblLastname = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblHouseNum = new javax.swing.JLabel();
        lblCommunity = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtHouseNum = new javax.swing.JTextField();
        txtCommunity = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        btnSaveProfile = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        AddVitalsPanel = new javax.swing.JPanel();
        lblBorder7 = new javax.swing.JLabel();
        lblBorder8 = new javax.swing.JLabel();
        lblHeader3 = new javax.swing.JLabel();
        lblTemperature = new javax.swing.JLabel();
        lblPressure = new javax.swing.JLabel();
        lblPulse = new javax.swing.JLabel();
        txtTemperature = new javax.swing.JTextField();
        txtPressure = new javax.swing.JTextField();
        txtPulse = new javax.swing.JTextField();
        btnSaveVitals = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnPreviousReports = new javax.swing.JButton();
        pnlTable = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPreviousReports = new javax.swing.JTable();

        jLayeredPane1.setLayout(new java.awt.CardLayout());

        ViewAllProfilePanel.setBackground(new java.awt.Color(239, 232, 232));

        lblBorder4.setBackground(new java.awt.Color(255, 204, 204));
        lblBorder4.setOpaque(true);

        lblBorder2.setBackground(new java.awt.Color(255, 204, 204));
        lblBorder2.setOpaque(true);

        lblHeader1.setBackground(new java.awt.Color(239, 232, 232));
        lblHeader1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblHeader1.setForeground(new java.awt.Color(0, 0, 0));
        lblHeader1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader1.setText("<html>View <b><span  font color=\"rgb(255,102,102)\">Profiles</span></b></html>");
        lblHeader1.setOpaque(true);

        tblDashboard.setBackground(new java.awt.Color(255, 255, 255));
        tblDashboard.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblDashboard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NAME", "AGE", "HOUSE NUM.", "COMMUNITY", "CITY", "IS PATIENT?"
            }
        ));
        tblDashboard.setGridColor(new java.awt.Color(255, 0, 51));
        tblDashboard.setSelectionBackground(new java.awt.Color(255, 204, 204));
        tblDashboard.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(tblDashboard);

        btnAddVitals.setBackground(new java.awt.Color(255, 255, 255));
        btnAddVitals.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAddVitals.setText("Add Vitals");
        btnAddVitals.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddVitals.setFocusPainted(false);
        btnAddVitals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddVitalsActionPerformed(evt);
            }
        });

        btnCreateProfile.setBackground(new java.awt.Color(255, 255, 255));
        btnCreateProfile.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCreateProfile.setText("Create Profile");
        btnCreateProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCreateProfile.setFocusPainted(false);
        btnCreateProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateProfileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ViewAllProfilePanelLayout = new javax.swing.GroupLayout(ViewAllProfilePanel);
        ViewAllProfilePanel.setLayout(ViewAllProfilePanelLayout);
        ViewAllProfilePanelLayout.setHorizontalGroup(
            ViewAllProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBorder4, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
            .addComponent(lblBorder2, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewAllProfilePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ViewAllProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewAllProfilePanelLayout.createSequentialGroup()
                        .addComponent(lblHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(203, 203, 203))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewAllProfilePanelLayout.createSequentialGroup()
                        .addGroup(ViewAllProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ViewAllProfilePanelLayout.createSequentialGroup()
                                .addComponent(btnCreateProfile)
                                .addGap(18, 18, 18)
                                .addComponent(btnAddVitals))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40))))
        );
        ViewAllProfilePanelLayout.setVerticalGroup(
            ViewAllProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewAllProfilePanelLayout.createSequentialGroup()
                .addComponent(lblBorder4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(ViewAllProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddVitals)
                    .addComponent(btnCreateProfile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 324, Short.MAX_VALUE)
                .addComponent(lblBorder2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLayeredPane1.add(ViewAllProfilePanel, "card3");

        CreateProfilePanel.setBackground(new java.awt.Color(239, 232, 232));

        lblBorder3.setBackground(new java.awt.Color(255, 204, 204));
        lblBorder3.setOpaque(true);

        lblBorder1.setBackground(new java.awt.Color(255, 204, 204));
        lblBorder1.setOpaque(true);

        lblHeader.setBackground(new java.awt.Color(239, 232, 232));
        lblHeader.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(0, 0, 0));
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("<html>Create a <b><span  font color=\"rgb(255,102,102)\">Profile</span></b></html> ");
        lblHeader.setOpaque(true);

        lblFirstName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFirstName.setText("First Name :");

        lblLastname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblLastname.setText("Last Name :");

        lblAge.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAge.setText("Age :");

        lblHouseNum.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHouseNum.setText("House No. :");

        lblCommunity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCommunity.setText("Community :");

        lblCity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCity.setText("City :");

        txtFirstName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNameActionPerformed(evt);
            }
        });

        txtLastName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        txtAge.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        txtHouseNum.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        txtCommunity.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        txtCity.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        btnSaveProfile.setBackground(new java.awt.Color(215, 254, 211));
        btnSaveProfile.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSaveProfile.setForeground(new java.awt.Color(72, 151, 64));
        btnSaveProfile.setText("SAVE PROFILE");
        btnSaveProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSaveProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveProfileActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("BACK");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setFocusPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CreateProfilePanelLayout = new javax.swing.GroupLayout(CreateProfilePanel);
        CreateProfilePanel.setLayout(CreateProfilePanelLayout);
        CreateProfilePanelLayout.setHorizontalGroup(
            CreateProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
            .addComponent(lblBorder3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(CreateProfilePanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButton3)
                .addGap(117, 117, 117)
                .addGroup(CreateProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CreateProfilePanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(CreateProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSaveProfile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(CreateProfilePanelLayout.createSequentialGroup()
                                .addGroup(CreateProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFirstName, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblLastname, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblAge, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblHouseNum, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblCommunity, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblCity, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(CreateProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHouseNum, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CreateProfilePanelLayout.setVerticalGroup(
            CreateProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreateProfilePanelLayout.createSequentialGroup()
                .addGroup(CreateProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CreateProfilePanelLayout.createSequentialGroup()
                        .addComponent(lblBorder3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CreateProfilePanelLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jButton3)))
                .addGap(112, 112, 112)
                .addGroup(CreateProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CreateProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastname)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CreateProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAge)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CreateProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHouseNum)
                    .addComponent(txtHouseNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CreateProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCommunity)
                    .addComponent(txtCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CreateProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(btnSaveProfile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                .addComponent(lblBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLayeredPane1.add(CreateProfilePanel, "card2");

        AddVitalsPanel.setBackground(new java.awt.Color(239, 232, 232));

        lblBorder7.setBackground(new java.awt.Color(255, 204, 204));
        lblBorder7.setOpaque(true);

        lblBorder8.setBackground(new java.awt.Color(255, 204, 204));
        lblBorder8.setOpaque(true);

        lblHeader3.setBackground(new java.awt.Color(239, 232, 232));
        lblHeader3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblHeader3.setForeground(new java.awt.Color(0, 0, 0));
        lblHeader3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader3.setText("<html>Add <b><span  font color=\"rgb(255,102,102)\">Vitals</span></b></html> ");
        lblHeader3.setOpaque(true);

        lblTemperature.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTemperature.setText("Temperature :");

        lblPressure.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPressure.setText("Blood Pressure :");

        lblPulse.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPulse.setText("Pulse :");

        txtTemperature.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtTemperature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTemperatureActionPerformed(evt);
            }
        });

        txtPressure.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        txtPulse.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        btnSaveVitals.setBackground(new java.awt.Color(215, 254, 211));
        btnSaveVitals.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSaveVitals.setForeground(new java.awt.Color(72, 151, 64));
        btnSaveVitals.setText("SAVE VITALS");
        btnSaveVitals.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSaveVitals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveVitalsActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setText("BACK");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setFocusPainted(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        lblId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblId.setText("ID: ");

        txtId.setEditable(false);
        txtId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblName.setText("Name: ");

        txtName.setEditable(false);
        txtName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        btnPreviousReports.setBackground(new java.awt.Color(255, 204, 102));
        btnPreviousReports.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPreviousReports.setForeground(new java.awt.Color(204, 102, 0));
        btnPreviousReports.setText("PREVIOUS REPORTS");
        btnPreviousReports.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPreviousReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousReportsActionPerformed(evt);
            }
        });

        pnlTable.setBackground(new java.awt.Color(239, 232, 232));

        tblPreviousReports.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblPreviousReports.setForeground(new java.awt.Color(0, 0, 0));
        tblPreviousReports.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "DATE/TIME"
            }
        ));
        tblPreviousReports.setSelectionBackground(new java.awt.Color(255, 204, 204));
        jScrollPane2.setViewportView(tblPreviousReports);

        javax.swing.GroupLayout pnlTableLayout = new javax.swing.GroupLayout(pnlTable);
        pnlTable.setLayout(pnlTableLayout);
        pnlTableLayout.setHorizontalGroup(
            pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        pnlTableLayout.setVerticalGroup(
            pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout AddVitalsPanelLayout = new javax.swing.GroupLayout(AddVitalsPanel);
        AddVitalsPanel.setLayout(AddVitalsPanelLayout);
        AddVitalsPanelLayout.setHorizontalGroup(
            AddVitalsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBorder8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblBorder7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(AddVitalsPanelLayout.createSequentialGroup()
                .addGroup(AddVitalsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddVitalsPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(AddVitalsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AddVitalsPanelLayout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addGap(117, 117, 117)
                                .addComponent(lblHeader3, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnPreviousReports)))
                    .addGroup(AddVitalsPanelLayout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addGroup(AddVitalsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSaveVitals, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(AddVitalsPanelLayout.createSequentialGroup()
                                .addGroup(AddVitalsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTemperature, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblPressure, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblPulse, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblId, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblName, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(AddVitalsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPressure, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPulse, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(pnlTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(120, 216, Short.MAX_VALUE))
        );
        AddVitalsPanelLayout.setVerticalGroup(
            AddVitalsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddVitalsPanelLayout.createSequentialGroup()
                .addGroup(AddVitalsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddVitalsPanelLayout.createSequentialGroup()
                        .addComponent(lblBorder7, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblHeader3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AddVitalsPanelLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jButton5)))
                .addGap(18, 18, 18)
                .addComponent(btnPreviousReports)
                .addGap(31, 31, 31)
                .addGroup(AddVitalsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName))
                .addGap(16, 16, 16)
                .addGroup(AddVitalsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddVitalsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTemperature)
                    .addComponent(txtTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddVitalsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPressure)
                    .addComponent(txtPressure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddVitalsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPulse)
                    .addComponent(txtPulse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(btnSaveVitals)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(pnlTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(lblBorder8, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLayeredPane1.add(AddVitalsPanel, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameActionPerformed

    /**
     * Save the person profile details
     *
     * @param evt
     */
    private void btnSaveProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveProfileActionPerformed
        Person person = people.addPeople();
        person.setFirstName(txtFirstName.getText());
        person.setLastName(txtLastName.getText());
        person.setAge(txtAge.getText());
        person.setResidence(txtHouseNum.getText());
        person.setCommunity(txtCommunity.getText());
        person.setCity(txtCity.getText());

        // Assign a random number as the ID
        Random randomNum = new Random();
        int randomCustomerId = randomNum.nextInt(65536 - 32768);
        person.setId(randomCustomerId);

        JOptionPane.showMessageDialog(this, "Profile saved. Your ID is: " + randomCustomerId);
        txtFirstName.setText("");
        txtLastName.setText("");
        txtAge.setText("");
        txtHouseNum.setText("");
        txtCommunity.setText("");
        txtCity.setText("");

        // Switch the card layout
        jLayeredPane1.removeAll();
        jLayeredPane1.add(ViewAllProfilePanel);
        jLayeredPane1.revalidate();
        jLayeredPane1.repaint();

        // Populate the table
        populateTable();
    }//GEN-LAST:event_btnSaveProfileActionPerformed

    /**
     * Create Profile button click, switch the card layout to the creation panel
     *
     * @param evt
     */
    private void btnCreateProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateProfileActionPerformed
        jLayeredPane1.removeAll();
        jLayeredPane1.add(CreateProfilePanel);
        jLayeredPane1.revalidate();
        jLayeredPane1.repaint();
    }//GEN-LAST:event_btnCreateProfileActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jLayeredPane1.removeAll();
        jLayeredPane1.add(ViewAllProfilePanel);
        jLayeredPane1.revalidate();
        jLayeredPane1.repaint();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnAddVitalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddVitalsActionPerformed
        int selectedRowIndex = tblDashboard.getSelectedRow();

        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row first");
            return;
        } else {
            // Style the JTable header
            JTableHeader tableHeader = tblPreviousReports.getTableHeader();
            tableHeader.setFont(new Font("Segoe UI", Font.BOLD, 12));
            ((DefaultTableCellRenderer) tableHeader.getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);

            jLayeredPane1.removeAll();
            jLayeredPane1.add(AddVitalsPanel);
            jLayeredPane1.revalidate();
            jLayeredPane1.repaint();
            DefaultTableModel model = (DefaultTableModel) tblDashboard.getModel();
            Person selectedPerson = (Person) model.getValueAt(selectedRowIndex, 0);
            VitalSigns vitalSigns = new VitalSigns(selectedPerson.getId(), selectedPerson.getFirstName(), selectedPerson.getLastName());
            txtId.setText(String.valueOf(vitalSigns.getId()));
            id = vitalSigns.getId();
            txtName.setText(vitalSigns.getFullName());

            // if the person is a patient already, display previous reports
            if (selectedPerson.isIsPatient()) {
                btnPreviousReports.setVisible(true);
            }
        }
    }//GEN-LAST:event_btnAddVitalsActionPerformed

    private void txtTemperatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTemperatureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTemperatureActionPerformed

    private void btnSaveVitalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveVitalsActionPerformed
        int selectedRowIndex = tblDashboard.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tblDashboard.getModel();
        Person selectedPerson = (Person) model.getValueAt(selectedRowIndex, 0);
        VitalSigns vitalSigns = new VitalSigns(selectedPerson.getId(), selectedPerson.getFirstName(), selectedPerson.getLastName());
        vitalSigns.setTemperature(Integer.parseInt(txtTemperature.getText()));
        vitalSigns.setBloodPressure(Integer.parseInt(txtPressure.getText()));
        vitalSigns.setPulse(Integer.parseInt(txtPulse.getText()));
        selectedPerson.updateAsAPatient(selectedPerson.getId(), people);

        Calendar calendar = Calendar.getInstance();
        vitalSigns.setDate(calendar.getTime());

        Patient patient = patientDir.addPatients();
        patient.setPerson(selectedPerson);

        Encounter encounter = encounterHistory.addEncounter();
        encounter.setVitalSigns(vitalSigns);
        patient.setEncounterHistory(encounterHistory);
        System.out.println(encounterHistory.getEncounterHistory().size());

        JOptionPane.showMessageDialog(this, "Vitals added for ID: " + selectedPerson.getId());
        txtName.setText("");
        txtId.setText("");
        txtTemperature.setText("");
        txtPressure.setText("");
        txtPulse.setText("");
        pnlTable.setVisible(false);
        jLayeredPane1.removeAll();
        jLayeredPane1.add(ViewAllProfilePanel);
        jLayeredPane1.revalidate();
        jLayeredPane1.repaint();
        populateTable();
    }//GEN-LAST:event_btnSaveVitalsActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jLayeredPane1.removeAll();
        jLayeredPane1.add(ViewAllProfilePanel);
        jLayeredPane1.revalidate();
        jLayeredPane1.repaint();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnPreviousReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousReportsActionPerformed
        pnlTable.setVisible(true);
        Patient patient = returnPatientObject(id);
        populatePreviousReports(patient);
    }//GEN-LAST:event_btnPreviousReportsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddVitalsPanel;
    private javax.swing.JPanel CreateProfilePanel;
    private javax.swing.JPanel ViewAllProfilePanel;
    private javax.swing.JButton btnAddVitals;
    private javax.swing.JButton btnCreateProfile;
    private javax.swing.JButton btnPreviousReports;
    private javax.swing.JButton btnSaveProfile;
    private javax.swing.JButton btnSaveVitals;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblBorder1;
    private javax.swing.JLabel lblBorder2;
    private javax.swing.JLabel lblBorder3;
    private javax.swing.JLabel lblBorder4;
    private javax.swing.JLabel lblBorder7;
    private javax.swing.JLabel lblBorder8;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCommunity;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblHeader1;
    private javax.swing.JLabel lblHeader3;
    private javax.swing.JLabel lblHouseNum;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblLastname;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPressure;
    private javax.swing.JLabel lblPulse;
    private javax.swing.JLabel lblTemperature;
    private javax.swing.JPanel pnlTable;
    private javax.swing.JTable tblDashboard;
    private javax.swing.JTable tblPreviousReports;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCommunity;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtHouseNum;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPressure;
    private javax.swing.JTextField txtPulse;
    private javax.swing.JTextField txtTemperature;
    // End of variables declaration//GEN-END:variables

    /**
     * Populate JTable
     *
     */
    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblDashboard.getModel();
        model.setRowCount(0);

        for (Person person : people.getPeople()) {
            Object[] row = new Object[7];
            row[0] = person;
            row[1] = person.getFirstName() + ' ' + person.getLastName();
            row[2] = person.getAge();
            row[3] = person.getResidence();
            row[4] = person.getCommunity();
            row[5] = person.getCity();

            if (person.isIsPatient()) {
                row[6] = "YES";
            } else {
                row[6] = "NO";
            }
            model.addRow(row);
        }
        Patient patient = new Patient();
    }

    // Return Person Directory list
    public PersonDirectory returnPersonDirectory() {
        return people;
    }

    // Return Patient Directory list
    public PatientDirectory returnPatientDirectory() {
        return patientDir;
    }

    // Return Encounter History list
    public EncounterHistory returnEncounterHistory() {
        return encounterHistory;
    }

    /**
     * Populate encounter history
     *
     */
    private void populatePreviousReports(Patient patient) {
        DefaultTableModel model = (DefaultTableModel) tblPreviousReports.getModel();
        model.setRowCount(0);

        for (Encounter enounter : patient.getEncounterHistory().getEncounterHistory()) {
            Object[] row = new Object[1];
            row[0] = enounter.getVitalSigns().getDate();
            model.addRow(row);
        }
    }

    /**
     * Return a patient object whose id matches
     *
     * @param id
     * @return
     */
    private Patient returnPatientObject(int id) {
        Patient newPatient = new Patient();
        for (Patient patient : patientDir.getPatientList()) {
            if (patient.getPerson().getId() == id) {
                newPatient = patient;
            }
        }
        return newPatient;
    }
}
